CREATE TABLE MYSTUDENTS(
ID INT,
name VARCHAR(100),
grade VARCHAR (10),
marks DECIMAL(5,2)
);
INSERT INTO MYSTUDENTS(ID,name,grade,marks) VALUES
(1,"OMOR FARUK","F",85.50);
SELECT * FROM MYSTUDENTS;
INSERT INTO MYSTUDENTS(ID,name,grade,marks) VALUES
(1,"VIM PAUL","V",99.50);
INSERT INTO MYSTUDENTS(ID,name,grade,marks) VALUES
(1,"PALLAB","A+",100.0);

